//
//  MainModels.swift
//  piRainbow
//
//  Created by Antonio Gonzalez Hidalgo on 23/05/2020.
//  Copyright (c) 2020 Antonio Gonzalez Hidalgo. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {

  enum PiNumbers {

    struct Request {
      let start: Int
      let numberOfDigits: Int
    }

    struct Response {
      let components: [CGFloat]
    }

    struct ViewModel {
      let colors: [PiColor]
    }

  }
}
